name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-latest

   steps:
    - name: Download repository
      uses: actions/checkout@v4
   
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Setup caches
      uses: actions/cache@v4
      with:
        restore-keys: ${{ runner.os }}-node-
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        path: ~/.npm
    
    - name: Install dependencies
      run: npm ci

    - name: Build website
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build